# SERIES

In [312]:
import numpy as np
import pandas as pd

In [313]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1: 10, 2:20, 3:30}

In [314]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [315]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [316]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [317]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# DataFrame

In [318]:
data = {

    'Name': ['Jhon', 'Jack', 'Ray'],
    'Age': [28, 35, 22],
    'City': ['Paris', 'NewYork', 'LA'],
    'Salary': [30000, 25000, 75000]


    
}

In [319]:
df = pd.DataFrame(data)
df

   Name  Age     City  Salary
0  Jhon   28    Paris   30000
1  Jack   35  NewYork   25000
2   Ray   22       LA   75000

In [320]:
data_list = [
    [ 'Jhon', 28, 'paris', 30000],
    [ 'Will', 35, 'Newyork', 50000],
    [ 'Ray', 33,  'London', 60000],
    [ 'Jack', 25,  'LA', 1000000],
    [ 'Kai', 25,   'LA', 1000000]]
columns = ['Name', 'Age', 'City', 'Salary']
df = pd.DataFrame(data_list)
df

      0   1        2        3
0  Jhon  28    paris    30000
1  Will  35  Newyork    50000
2   Ray  33   London    60000
3  Jack  25       LA  1000000
4   Kai  25       LA  1000000

In [321]:
df = pd.DataFrame(data_list, columns=columns)  #manually setting cloumn
df

   Name  Age     City   Salary
0  Jhon   28    paris    30000
1  Will   35  Newyork    50000
2   Ray   33   London    60000
3  Jack   25       LA  1000000
4   Kai   25       LA  1000000

# Selecting and Indexing of Column

In [322]:
df['Name']

0    Jhon
1    Will
2     Ray
3    Jack
4     Kai
Name: Name, dtype: object

In [323]:
df[['Name', 'Age']]

   Name  Age
0  Jhon   28
1  Will   35
2   Ray   33
3  Jack   25
4   Kai   25

# Creating New Column

In [324]:
df['College'] = ['MIT', 'Harward', 'Stanford', 'MIt', 'LA']
df

   Name  Age     City   Salary   College
0  Jhon   28    paris    30000       MIT
1  Will   35  Newyork    50000   Harward
2   Ray   33   London    60000  Stanford
3  Jack   25       LA  1000000       MIt
4   Kai   25       LA  1000000        LA

# Removing Column

In [325]:
df.drop('City', axis=1, inplace=True)  # axis 1 nhi likha phir axis 0 defualt hota hai aur search by row hota hai isliye column ke liye axis 1 likkho
df                                    # inplace true matlab permanently delete karo , agar nhi likha phir bus ek copy mai delete hoga aur next time df call krne par phir se dikhega

   Name  Age   Salary   College
0  Jhon   28    30000       MIT
1  Will   35    50000   Harward
2   Ray   33    60000  Stanford
3  Jack   25  1000000       MIt
4   Kai   25  1000000        LA

# Removing Row

In [326]:
df.drop(3, axis=0, inplace = True)
df

   Name  Age   Salary   College
0  Jhon   28    30000       MIT
1  Will   35    50000   Harward
2   Ray   33    60000  Stanford
4   Kai   25  1000000        LA

# Acess Row

In [327]:

df.loc[1]

Name          Will
Age             35
Salary       50000
College    Harward
Name: 1, dtype: object

In [328]:
df.loc[[1, 2]]

   Name  Age  Salary   College
1  Will   35   50000   Harward
2   Ray   33   60000  Stanford

# Slicing

In [329]:
df.loc[[0,1], ['Salary', 'College']] #slicing

   Salary  College
0   30000      MIT
1   50000  Harward

In [330]:
df

   Name  Age   Salary   College
0  Jhon   28    30000       MIT
1  Will   35    50000   Harward
2   Ray   33    60000  Stanford
4   Kai   25  1000000        LA

# Condition Selecting

In [331]:
#Age less than 30

df[df['Age'] < 30]

   Name  Age   Salary College
0  Jhon   28    30000     MIT
4   Kai   25  1000000      LA

In [332]:
#Age less Than 30 And College MIT
df[(df['Age'] < 30) & (df['College'] == 'MIT')]

   Name  Age  Salary College
0  Jhon   28   30000     MIT

# Finding Missing Data

In [333]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [334]:
df.isna().sum()  #total null value in column

A    1
B    0
C    2
D    3
dtype: int64

In [335]:
df.isna().any()  #does any column has not null value it would be 'False'

A     True
B    False
C     True
D     True
dtype: bool

# Remove Null Value

In [336]:
df.dropna()  # it will select by rows

     A  B    C    D
0  1.0  1  1.0  1.0

In [337]:
df.dropna(thresh = 3)  # row with atleast 3 non null value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling the Missing Data

In [338]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

df.fillna(0)  # fill not null value by 0

In [339]:
values = {'A':0, 'B':100, 'C':200, 'D':400}  # fill null value by index (cloumn wise)
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  200.0  400.0
4  5.0  5  200.0    5.0

# Merging Joining Concat

In [340]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [341]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [342]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [343]:
pd.merge(employees, salaries, on = 'employee_id', how = 'inner') # on = kiske bases pe merge
                                                    # how = 'inner' employee_id pe common parts pe merge

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [344]:
pd.merge(employees, salaries, on = 'employee_id', how = 'outer')  # how = "outer" common and uncommon

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [345]:
pd.merge(employees, salaries, on = 'employee_id', how = 'left')  # how = "left" merge based on employees(left ke sare cell)

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [346]:
pd.merge(employees, salaries, on = 'employee_id', how = 'right')  # how = "right" merge based on employees(left ke sare cell)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatination of 2 Dataframes

In [347]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [348]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [349]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [350]:
pd.concat([df1, df2])   # [df1, df2] upar df1 aur niche df2 angar , [df2, df1] upadr df2 niche df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

  # joining 2 dataframes

In [351]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [352]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [353]:
df2

   score
2     85
3     90
4     75

In [354]:
df1.join(df2) # df1 ke index jo df2 mai common hai

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

# GroupBy

In [355]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [356]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum() 
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [357]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [358]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [359]:
#multiple value to combine krke value

print("mean: ",df['Sales'].mean())
print("median: ",df['Sales'].median())
print("max: ",df['Sales'].max())
print("min: ",df['Sales'].min())
print("count: ",df['Sales'].count())
print("std: ",df['Sales'].std())

mean:  187.5
median:  190.0
max:  300
min:  100
count:  8
std:  66.06274074155351

In [360]:
df['Sales'].agg(['mean', 'median', 'max', 'min', 'count'])

mean      187.5
median    190.0
max       300.0
min       100.0
count       8.0
Name: Sales, dtype: float64

# Operations

In [367]:
df3 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df3

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [368]:
df3.shape

(5, 3)

In [369]:
df3.columns

Index(['A', 'B', 'C'], dtype='object')

In [370]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [371]:
df3.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [372]:
df3['A'] +10
df3

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [373]:
def square(x) :
    return x ** 2

In [378]:
df3['B'] = df3['B'].apply(square)
df3

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500